# Kaggle kernel body -- GENERATED by tools/pack_kernel.py, do not edit by hand.
# Self-contained: the repo source is embedded below as a base64 tar.gz, because
# `kaggle kernels push` carries only this one file and the repo is private.
#
# Runs the resumable Optuna league (league/league.py) for a bounded time budget
# against the full opponent pool (V9/V11/V12/V14 + main_leader, the non-lineage
# opponent) and writes main.py (best champion export), decision.json and the
# resumable checkpoint.zip to /kaggle/working. This is a real TPE search over the
# v15 parameter space, not the one-shot validation gate that train.yml runs.
#
# league.py forces multiprocessing's 'spawn' start method, which re-imports this
# file's top level in every worker process. Everything with a side effect (the
# tarfile extract, the actual search) MUST stay under the __main__ guard below, or
# each spawned worker re-extracts and re-launches the whole search recursively.
import base64, contextlib, io, json, os, subprocess, sys, tarfile
from pathlib import Path

WORK = "/kaggle/working"
SRC = "/tmp/kaggriculture_src"          # /kaggle itself is not writable
PAYLOAD = "__PAYLOAD__"
MINUTES = __MINUTES__


def main():
    os.makedirs(SRC, exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(base64.b64decode(PAYLOAD)), mode="r:gz") as tar:
        try:
            tar.extractall(SRC, filter="data")      # py>=3.12
        except TypeError:
            tar.extractall(SRC)
    os.chdir(SRC)
    print("python", sys.version)
    print("unpacked:", sorted(os.listdir(".")), flush=True)

    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"],
                   check=True)

    config = dict(
        output_dir=WORK, time_budget_minutes=MINUTES, max_cycles=30,
        general_trials=14, exploiter_trials=6,
        workers=min(4, os.cpu_count() or 2),
        train_seeds=3, selection_seeds=4, holdout_seeds=24, finalists=2, selfplay_seeds=2,
        # Raised 2026-09-20: the promoted V15 candidate cleared the 55% gate floor
        # against main_leader (81.2%) and still only wins 52.8% of real games -- the
        # gate is a floor against regression, not a target. stop_on_target should not
        # fire on "good enough to pass the gate."
        history_size=4, target_mean_cash=140_000, target_win_rate=.90, target_80k_rate=.70,
        stop_on_target=True, stagnation_cycles=6, v9_win_rate=.80, champion_win_rate=.60,
        min_opponent_win_rate=.55, max_decision_seconds=.80, extra_opponents=[],
        checkpoint_copy="",
    )
    Path(WORK).mkdir(parents=True, exist_ok=True)
    (Path(WORK) / "search_config.json").write_text(json.dumps(config, indent=2))
    print("search config:", json.dumps(config, indent=2), flush=True)

    sys.path.insert(0, str(Path("league").resolve()))
    import league  # noqa

    with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
        import kaggle_environments
    if kaggle_environments.__version__ != "1.32.7":
        raise ValueError("Simulator version mismatch: pinned 1.32.7, got "
                          + kaggle_environments.__version__)

    import concurrent.futures, multiprocessing
    with concurrent.futures.ProcessPoolExecutor(
            max_workers=config["workers"], mp_context=multiprocessing.get_context("spawn")) as pool:
        engine = league.League(config, pool)
        if engine.state["cycle"] == 0 and not engine.state.get("warm_starts"):
            # Real-replay diagnosis (2026-09-20, analysis/REPORT_deployment_diagnosis.md):
            # the promoted V15 candidate never buys a 4th quadrant (land=3 hard ceiling)
            # and is 10x behind on day-10 cash. Seed the search with that hypothesis
            # instead of waiting for TPE to rediscover it by chance.
            import support
            hypothesis = league.warm_params(dict(support.BASE, land=4, land_deadline=10,
                expansion_hands=6, land_util=0.30, survival_bias=0.45, hire_pace=1))
            engine.state["warm_starts"] = [hypothesis]
            print("seeded warm-start hypothesis (land=4, early expansion):", hypothesis, flush=True)
        try:
            engine.run()
        except (TimeoutError, KeyboardInterrupt):
            engine.save("paused_resume_available")
            print("Paused on time budget. Checkpoint is resumable.", flush=True)
        except Exception:
            import shutil
            shutil.copyfile(engine.root / engine.state["champion"], engine.root / "main.py")
            engine.save("error_resume_available")
            raise
        print("FINAL", json.dumps(json.loads((engine.root / "decision.json").read_text()), indent=2),
              flush=True)

    print("kernel done ->", sorted(os.listdir(WORK)))


if __name__ == "__main__":
    main()
