# Kaggle kernel body -- GENERATED by tools/pack_kernel.py, do not edit by hand.
# Self-contained: the repo source is embedded below as a base64 tar.gz, because
# `kaggle kernels push` carries only this one file and the repo is private.
# Runs the bounded validation and writes main.py + validation.json to /kaggle/working.
import base64, io, os, subprocess, sys, tarfile

WORK = "/kaggle/working"
SRC = "/tmp/kaggriculture_src"          # /kaggle itself is not writable
PAYLOAD = "__PAYLOAD__"

os.makedirs(SRC, exist_ok=True)
with tarfile.open(fileobj=io.BytesIO(base64.b64decode(PAYLOAD)), mode="r:gz") as tar:
    try:
        tar.extractall(SRC, filter="data")      # py>=3.12
    except TypeError:
        tar.extractall(SRC)
os.chdir(SRC)
print("python", sys.version)
print("unpacked:", sorted(os.listdir(".")), flush=True)

subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"],
               check=True)
# Bounded validation: current candidate vs the league on fresh holdout seeds; exports
# main.py and validation.json. (Full Optuna search is a separate, longer kernel.)
subprocess.run([sys.executable, "experiments/validate.py", "--out", WORK,
                "--seeds", "__SEEDS__", "--seed-base", "__SEED_BASE__"], check=True)
print("kernel done ->", sorted(os.listdir(WORK)))
