# Kaggle kernel body -- GENERATED by tools/pack_kernel.py, do not edit by hand.
# Self-contained: the repo source is embedded below as a base64 tar.gz, because
# `kaggle kernels push` carries only this one file and the repo is private.
#
# Runs the resumable Optuna league (league/league.py) for a bounded time budget
# against the full opponent pool (V9/V11/V12/V14 + main_leader, the non-lineage
# opponent) and writes main.py (best champion export), decision.json and the
# resumable checkpoint.zip to /kaggle/working. This is a real TPE search over the
# v15 parameter space, not the one-shot validation gate that train.yml runs.
#
# league.py forces multiprocessing's 'spawn' start method, which re-imports this
# file's top level in every worker process. Everything with a side effect (the
# tarfile extract, the actual search) MUST stay under the __main__ guard below, or
# each spawned worker re-extracts and re-launches the whole search recursively.
import base64, contextlib, glob, io, json, os, subprocess, sys, tarfile, zipfile
from pathlib import Path

WORK = "/kaggle/working"
SRC = "/tmp/kaggriculture_src"          # /kaggle itself is not writable
PAYLOAD = "__PAYLOAD__"
MINUTES = __MINUTES__


def main():
    os.makedirs(SRC, exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(base64.b64decode(PAYLOAD)), mode="r:gz") as tar:
        try:
            tar.extractall(SRC, filter="data")      # py>=3.12
        except TypeError:
            tar.extractall(SRC)
    os.chdir(SRC)
    print("python", sys.version)
    print("unpacked:", sorted(os.listdir(".")), flush=True)

    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"],
                   check=True)

    config = dict(
        output_dir=WORK, time_budget_minutes=MINUTES, max_cycles=30,
        general_trials=14, exploiter_trials=6,
        workers=min(4, os.cpu_count() or 2),
        train_seeds=3, selection_seeds=4, holdout_seeds=24, finalists=2, selfplay_seeds=2,
        # Raised 2026-09-20: the promoted V15 candidate cleared the 55% gate floor
        # against main_leader (81.2%) and still only wins 52.8% of real games -- the
        # gate is a floor against regression, not a target. stop_on_target should not
        # fire on "good enough to pass the gate."
        history_size=4, target_mean_cash=140_000, target_win_rate=.90, target_80k_rate=.70,
        stop_on_target=True, stagnation_cycles=6, v9_win_rate=.80, champion_win_rate=.60,
        min_opponent_win_rate=.55, max_decision_seconds=.80, extra_opponents=[],
        checkpoint_copy="",
    )
    Path(WORK).mkdir(parents=True, exist_ok=True)
    # tools/pack_kernel.py --checkpoint-dataset attaches a Kaggle Dataset holding a
    # prior run's checkpoint.zip (kernel-metadata.json dataset_sources); Kaggle mounts
    # it read-only under /kaggle/input/<dataset-slug>/. Unpack it into WORK before
    # League() is built so it resumes state.json/study.db/agents/candidates/reports
    # instead of starting cycle 0. Absent for a fresh run -- nothing to find, proceed
    # as before. League's own manifest check still refuses a mismatched checkpoint
    # (stale league.py/support.py/policy_template.py/fixed-agent hashes) rather than
    # silently corrupting it.
    checkpoints = glob.glob("/kaggle/input/*/checkpoint.zip")
    if checkpoints:
        with zipfile.ZipFile(checkpoints[0]) as z:
            z.extractall(WORK)
        print("resumed from checkpoint dataset:", checkpoints[0], sorted(os.listdir(WORK)), flush=True)
    (Path(WORK) / "search_config.json").write_text(json.dumps(config, indent=2))
    print("search config:", json.dumps(config, indent=2), flush=True)

    sys.path.insert(0, str(Path("league").resolve()))
    import league  # noqa

    with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
        import kaggle_environments
    if kaggle_environments.__version__ != "1.32.7":
        raise ValueError("Simulator version mismatch: pinned 1.32.7, got "
                          + kaggle_environments.__version__)

    import concurrent.futures, multiprocessing
    with concurrent.futures.ProcessPoolExecutor(
            max_workers=config["workers"], mp_context=multiprocessing.get_context("spawn")) as pool:
        engine = league.League(config, pool)
        # One warm start, not a guess this time. Measured 2026-09-23: every new
        # lever is HARMFUL on its own -- plant_urgency alone fills the land but
        # drains cash to 2.7 and hires zero hands; cash_discount alone switches to
        # short-cycle crops but, at our ~100 plants a game, just harvests less value
        # from the same few tiles. They only pay together, which is precisely the
        # structure TPE is for and precisely what hand-picking cannot find (four
        # straight failures). Seeding one joint point costs a single trial.
        engine.state.setdefault('warm_starts',[]).append(league.warm_params(dict(
            league.BASE, cash_discount=.80, cash_patience=8000., plant_urgency=3.,
            seed_fill=8, tiles_per_unit=7, hire_pace=1, crop_style='quick',
            survival_bias=1., fert_in_window=1, land_deadline=12, expansion_hands=7,
            strawberry_target=30)))
        try:
            engine.run()
        except (TimeoutError, KeyboardInterrupt):
            engine.save("paused_resume_available")
            print("Paused on time budget. Checkpoint is resumable.", flush=True)
        except Exception:
            import shutil
            shutil.copyfile(engine.root / engine.state["champion"], engine.root / "main.py")
            engine.save("error_resume_available")
            raise
        print("FINAL", json.dumps(json.loads((engine.root / "decision.json").read_text()), indent=2),
              flush=True)

    print("kernel done ->", sorted(os.listdir(WORK)))


if __name__ == "__main__":
    main()
