"""Generate the GitHub Pages status dashboard into docs/.

IMPORTANT -- this site is PUBLIC. GitHub Pages on a private repo is publicly
readable on this plan, so only publish what is already public knowledge: our
leaderboard standing and our own episode results (both visible on Kaggle anyway).
Strategy analysis (analysis/*.md), policy parameters and agent source stay in the
private repo and must not be written into docs/.
"""
import csv, json, statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FEED = ROOT / "analysis" / "feedback"
DOCS = ROOT / "docs"


def read_leaderboard():
    files = sorted((FEED / "lb_extract").glob("*.csv")) if (FEED / "lb_extract").exists() else []
    if not files:
        return None
    rows = list(csv.DictReader(open(files[-1], encoding="utf-8-sig", errors="replace")))
    scores = [float(r["Score"]) for r in rows]
    mine = [r for r in rows if "nickazaria" in (r.get("TeamMemberUserNames") or "").lower()]
    return {"teams": len(rows), "leader": scores[0], "median": statistics.median(scores),
            "me": mine[0] if mine else None,
            "top": rows[:10]}


def read_submissions():
    f = FEED / "submissions.csv"
    if not f.exists():
        return []
    return list(csv.DictReader(open(f, encoding="utf-8", errors="replace")))[:8]


def read_episodes():
    f = FEED / "episodes.json"
    if not f.exists():
        return {}
    return json.loads(f.read_text(encoding="utf-8"))


def main():
    DOCS.mkdir(exist_ok=True)
    out = ["---", "title: Kaggriculture agent status", "---", "",
           "# Kaggriculture agent — status", ""]

    lb = read_leaderboard()
    if lb and lb["me"]:
        m = lb["me"]
        out += ["## Standing", "",
                f"**Rank {int(m['Rank']):,} of {lb['teams']:,}** — score {m['Score']}  ",
                f"Field median {lb['median']:.1f} · leader {lb['leader']:.1f}", "",
                "> Ratings drift: the same unchanged agent has read 60 points apart",
                "> within an afternoon. Treat small differences as noise.", ""]

    subs = read_submissions()
    if subs:
        out += ["## Recent submissions", "",
                "| agent | submitted (UTC) | score |", "|---|---|---:|"]
        for s in subs:
            out.append(f"| `{s.get('fileName','')}` | {s.get('date','')[:16]} | {s.get('publicScore') or '—'} |")
        out.append("")

    eps = read_episodes()
    if eps:
        out += ["## Real games played", "",
                "| agent | games | win rate | our cash | opponent cash |", "|---|---:|---:|---:|---:|"]
        for sid, d in eps.items():
            rows = d.get("episodes") or []
            if not rows:
                continue
            out.append("| `%s` | %d | %.1f%% | %s | %s |" % (
                d.get("file", sid), len(rows), 100 * statistics.mean(r["won"] for r in rows),
                f"{statistics.mean(r['our_cash'] for r in rows):,.0f}",
                f"{statistics.mean(r['opp_cash'] for r in rows):,.0f}"))
        out.append("")

    if lb:
        out += ["## Top of the leaderboard", "", "| # | team | score |", "|---:|---|---:|"]
        for r in lb["top"]:
            out.append(f"| {r['Rank']} | {r['TeamName']} | {r['Score']} |")
        out.append("")

    out += ["---", "",
            "Generated by `tools/build_site.py` from the CI feedback pull.",
            "Strategy analysis is kept in the private repository, not here."]
    (DOCS / "index.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    cfg = DOCS / "_config.yml"
    if not cfg.exists():
        cfg.write_text("theme: jekyll-theme-minimal\ntitle: Kaggriculture agent\n", encoding="utf-8")
    print("wrote", DOCS / "index.md")


if __name__ == "__main__":
    main()
