"""Generate the GitHub Pages site into docs/: status dashboard + analysis reports.

IMPORTANT -- this site is PUBLIC. GitHub Pages on a private repo is publicly readable
on this plan. Publishing the analysis reports here was an explicit owner decision
(2026-09-19): the engine mechanics, occupancy numbers and policy defects in them are
public and search-indexable while the competition is running.

Still NOT published, and must not be: agent source (`agents/*.py`), the policy
template and its parameter values, and the raw evidence dumps (`analysis/*.json`).
Those are what an opponent could run directly. Keep the Pages source pointed at
/docs, never at the repo root.
"""
import csv, json, shutil, statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FEED = ROOT / "analysis" / "feedback"
DOCS = ROOT / "docs"


def read_leaderboard():
    files = sorted((FEED / "lb_extract").glob("*.csv")) if (FEED / "lb_extract").exists() else []
    if not files:
        return None
    rows = list(csv.DictReader(open(files[-1], encoding="utf-8-sig", errors="replace")))
    scores = [float(r["Score"]) for r in rows]
    mine = [r for r in rows if "nickazaria" in (r.get("TeamMemberUserNames") or "").lower()]
    return {"teams": len(rows), "leader": scores[0], "median": statistics.median(scores),
            "me": mine[0] if mine else None,
            "top": rows[:10]}


def read_submissions():
    f = FEED / "submissions.csv"
    if not f.exists():
        return []
    return list(csv.DictReader(open(f, encoding="utf-8", errors="replace")))[:8]


def read_episodes():
    f = FEED / "episodes.json"
    if not f.exists():
        return {}
    return json.loads(f.read_text(encoding="utf-8"))


def publish_reports():
    """Copy analysis/*.md into docs/analysis/ and link them. Markdown reports only --
    never the .json evidence dumps or anything under agents/ or policy/."""
    src = ROOT / "analysis"
    dst = DOCS / "analysis"
    reports = sorted(src.glob("*.md"))
    if not reports:
        return []
    dst.mkdir(parents=True, exist_ok=True)
    lines = ["## Analysis", ""]
    for r in reports:
        body = r.read_text(encoding="utf-8")
        title = next((l.lstrip("# ").strip() for l in body.splitlines()
                      if l.startswith("# ")), r.stem)
        # Jekyll needs front matter to render these as pages with a title.
        (dst / r.name).write_text("---\ntitle: %s\n---\n\n%s" % (title.replace('"', "'"), body),
                                  encoding="utf-8")
        lines.append("- [%s](analysis/%s)" % (title, r.with_suffix(".html").name))
    lines.append("")
    return lines


def main():
    DOCS.mkdir(exist_ok=True)
    out = ["---", "title: Kaggriculture agent status", "---", "",
           "# Kaggriculture agent — status", ""]

    lb = read_leaderboard()
    if lb and lb["me"]:
        m = lb["me"]
        out += ["## Standing", "",
                f"**Rank {int(m['Rank']):,} of {lb['teams']:,}** — score {m['Score']}  ",
                f"Field median {lb['median']:.1f} · leader {lb['leader']:.1f}", "",
                "> Ratings drift: the same unchanged agent has read 60 points apart",
                "> within an afternoon. Treat small differences as noise.", ""]

    subs = read_submissions()
    if subs:
        out += ["## Recent submissions", "",
                "| agent | submitted (UTC) | score |", "|---|---|---:|"]
        for s in subs:
            out.append(f"| `{s.get('fileName','')}` | {s.get('date','')[:16]} | {s.get('publicScore') or '—'} |")
        out.append("")

    eps = read_episodes()
    if eps:
        out += ["## Real games played", "",
                "| agent | games | win rate | our cash | opponent cash |", "|---|---:|---:|---:|---:|"]
        for sid, d in eps.items():
            rows = d.get("episodes") or []
            if not rows:
                continue
            out.append("| `%s` | %d | %.1f%% | %s | %s |" % (
                d.get("file", sid), len(rows), 100 * statistics.mean(r["won"] for r in rows),
                f"{statistics.mean(r['our_cash'] for r in rows):,.0f}",
                f"{statistics.mean(r['opp_cash'] for r in rows):,.0f}"))
        out.append("")

    if lb:
        out += ["## Top of the leaderboard", "", "| # | team | score |", "|---:|---|---:|"]
        for r in lb["top"]:
            out.append(f"| {r['Rank']} | {r['TeamName']} | {r['Score']} |")
        out.append("")

    out += publish_reports()
    out += ["---", "",
            "Generated by `tools/build_site.py` from the CI feedback pull.",
            "Agent source and policy parameters are not published here."]
    (DOCS / "index.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    cfg = DOCS / "_config.yml"
    if not cfg.exists():
        cfg.write_text("theme: jekyll-theme-minimal\ntitle: Kaggriculture agent\n", encoding="utf-8")
    print("wrote", DOCS / "index.md")


if __name__ == "__main__":
    main()
